services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=Asia/Kuala_Lumpur
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./data:/home/node/.n8n-files/data
      - ./sample_outputs:/home/node/.n8n-files/sample_outputs
      - ./error_logs:/home/node/.n8n-files/error_logs